/**
 * Build-time catalog generator: Hetzner's OpenAPI specs -> src/generated/*.
 *
 * Run with `npm run codegen`. The catalog is committed rather than fetched or
 * parsed at runtime because every MCP client spawns this process fresh: the two
 * vendored specs are ~3.9 MB of JSON, and paying that parse on every stdio
 * start — before the first tool call — is a cost the user notices. CI re-runs
 * this and diffs `src/generated`, so upstream drift breaks the build loudly
 * instead of shipping a stale surface silently.
 *
 * Hetzner is not one API, so this generator reads N specs rather than one. The
 * surface travels with every row from here to the transport; nothing downstream
 * infers it. `robot` has no OpenAPI spec and is deferred, which is why the spec
 * list is a table rather than a pair of variables — adding Robot later is a new
 * entry plus a tag map, not a rewrite.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SURFACES } from '../src/types.js';
import type {
  CatalogMeta,
  CatalogOperation,
  DangerClass,
  HttpMethod,
  OperationFamily,
  Surface,
} from '../src/types.js';

// ---------------------------------------------------------------------------
// Pinned expectations — the tripwires
// ---------------------------------------------------------------------------

/**
 * Operations in each vendored spec. Asserted, not measured: a generator that
 * quietly adapts to whatever it is fed will happily emit a half-catalog after a
 * bad spec refresh, and a half-catalog is worse than no catalog because the
 * missing half looks like a capability the product does not have. Bump these
 * deliberately, in the same commit as the new spec.
 */
const EXPECTED_CLOUD_OPERATIONS = 189;
const EXPECTED_ACCOUNT_OPERATIONS = 32;

/**
 * Cloud GETs that accept `page`/`per_page`. Pinned for the same reason as the
 * counts above, but aimed at a different failure: pagination is derived from a
 * parameter name, so a spec that renamed `per_page` would leave every list
 * operation looking unpaginated and the tool layer would stop offering a
 * cursor. That failure is invisible in the operation count.
 */
const EXPECTED_PAGINATED_CLOUD_GETS = 38;

// ---------------------------------------------------------------------------
// Spec sources
// ---------------------------------------------------------------------------

interface SpecSource {
  surface: Surface;
  file: string;
  expectedOperations: number;
}

/**
 * `robot` is absent on purpose. Robot has no OpenAPI document — it is described
 * only in prose — so it is deferred to a later version rather than guessed at.
 * Nothing below is written for exactly two entries.
 */
const SPEC_SOURCES: readonly SpecSource[] = [
  {
    surface: 'cloud',
    file: 'hetzner-cloud.openapi.json',
    expectedOperations: EXPECTED_CLOUD_OPERATIONS,
  },
  {
    surface: 'hetzner',
    file: 'hetzner-api.openapi.json',
    expectedOperations: EXPECTED_ACCOUNT_OPERATIONS,
  },
];

// ---------------------------------------------------------------------------
// Danger overrides
// ---------------------------------------------------------------------------

/**
 * Hand-maintained. These are not DELETEs, so "gate the DELETEs" misses them,
 * yet each one destroys data that the API cannot give back.
 *
 * Keyed by `surface METHOD /path` rather than by operationId: the route is the
 * semantic identity, while the id is generated by upstream tooling and can be
 * renamed. The surface is part of the key because two surfaces may legitimately
 * serve the same path — `/storage_boxes/...` is account-scoped today, and Robot
 * has its own storage box routes waiting behind the deferred surface.
 *
 * Every entry must match exactly one operation or the generator fails. That
 * tripwire is the entire point: a renamed upstream route must not silently
 * downgrade a destructive operation to an ordinary write.
 */
const DESTRUCTIVE_OVERRIDE_ROUTES: readonly string[] = [
  // "Rebuilds a Server overwriting its disk with the content of an Image,
  // thereby destroying all data on the target Server."
  'cloud POST /servers/{id}/actions/rebuild',

  // "Imports a zone file, replacing all resource record sets." Every RRSet in
  // the zone is replaced in one call; the previous records are not retrievable.
  'cloud POST /zones/{id_or_name}/actions/import_zonefile',

  // "Overwrites the resource records (RRs) of an existing RRSet." The
  // record-level twin of import_zonefile, by the same mechanism. Gating it
  // costs nothing operationally because add_records, remove_records and
  // update_records remain available as ordinary writes for real edits — this
  // is specifically the blind replace-everything verb.
  'cloud POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/set_records',

  // "This will remove all newer Storage Box Snapshots and irrevocably delete
  // all data that was since written to the Storage Box."
  'hetzner POST /storage_boxes/{id}/actions/rollback_snapshot',
];

/**
 * Deliberately NOT overridden, recorded here because each was considered and
 * each will look like an omission to the next reader:
 *
 *  - `POST /firewalls/{id}/actions/set_rules` overwrites all rules, but it is
 *    the ONLY verb for editing them — there is no add_rule — so gating it would
 *    remove firewall editing rather than protect it. The rules are also fully
 *    readable beforehand and re-appliable, which is not true of a wiped disk.
 *  - `POST /servers/{id}/actions/reset` and `poweroff` document that they "may
 *    lead to data loss" by cutting power. They risk unflushed writes; they do
 *    not destroy data by design, and they are the standard recovery verbs for a
 *    hung machine. Gating recovery behind the destructive flag inverts the
 *    purpose of the flag.
 *  - `POST /servers/{id}/actions/change_type` copies the disk to a new machine
 *    and is one-way once `upgrade_disk` is true, but it destroys nothing. It is
 *    costly, not destructive.
 */

// ---------------------------------------------------------------------------
// Costly operations
// ---------------------------------------------------------------------------

/**
 * Opens a bill. NOT gated — the product deliberately keeps everything
 * non-destructive reachable — but flagged on every search result and in the
 * response, so the consequence is visible before the call rather than only on
 * the invoice.
 *
 * Same exact-match discipline as the destructive overrides: an entry that stops
 * matching fails the build, because a `create_server` that quietly lost its
 * costly flag is a bill nobody was warned about.
 *
 * The authority for what belongs here is `GET /pricing`, which returns exactly
 * one category per billable resource kind: `primary_ips`, `floating_ips`,
 * `image`, `volume`, `server_backup`, `server_types`, `load_balancer_types`.
 * Every cloud entry below maps onto one of them, and a test enforces that
 * congruence against the vendored spec. Certificates were considered and
 * dropped: Hetzner's managed certificates are free, and `/pricing` has no
 * category for them. A false positive is worse than a missing flag — the flag's
 * whole value is that the model can trust it, and one operation flagged costly
 * for free work teaches it to discount every true warning.
 */
const COSTLY_ROUTES: readonly string[] = [
  // Provisioning. Each of these starts charging the moment it succeeds.
  'cloud POST /servers',
  'cloud POST /volumes',
  'cloud POST /load_balancers',
  'cloud POST /floating_ips',
  'cloud POST /primary_ips',
  'hetzner POST /storage_boxes',

  // Snapshot storage is billed per GB of image size.
  'cloud POST /servers/{id}/actions/create_image',

  // "Enabling automatic backups will increase the price of the Server by 20%."
  'cloud POST /servers/{id}/actions/enable_backup',

  // Rate changes. Upsizing takes effect immediately and, for a Server whose
  // disk was upgraded, cannot be undone.
  'cloud POST /servers/{id}/actions/change_type',
  'cloud POST /load_balancers/{id}/actions/change_type',
  'hetzner POST /storage_boxes/{id}/actions/change_type',

  // "Volumes are billed by size and cannot be shrunk again."
  'cloud POST /volumes/{id}/actions/resize',
];

// ---------------------------------------------------------------------------
// Families
// ---------------------------------------------------------------------------

/**
 * OpenAPI tag -> family, per surface.
 *
 * Per surface because a tag is a label inside one document, not a global name.
 * Robot's "Servers" will mean leased physical hardware, which is a different
 * family from a Cloud Server; a single flat map would collapse the two and make
 * "reboot the server" ambiguous in exactly the way `Surface` exists to prevent.
 *
 * Resource-specific action tags fold into their resource: someone searching for
 * "reboot server" wants it filed under `servers`, not under a separate
 * `server-actions` bucket they would have to know to look in. The `actions`
 * family is reserved for the two generic Action-polling endpoints.
 *
 * An unmapped tag FAILS the build. Falling back to `other` would be the wrong
 * kindness — `other` is for genuinely uncategorised operations, and a silent
 * fallback turns "upstream added a product" into "twelve operations nobody can
 * find by family".
 */
const FAMILY_BY_TAG: Readonly<Partial<Record<Surface, Readonly<Record<string, OperationFamily>>>>> =
  {
    cloud: {
      Actions: 'actions',
      Certificates: 'certificates',
      'Certificate Actions': 'certificates',
      'Data Centers': 'datacenters',
      Firewalls: 'firewalls',
      'Firewall Actions': 'firewalls',
      'Floating IPs': 'floating-ips',
      'Floating IP Actions': 'floating-ips',
      ISOs: 'isos',
      Images: 'images',
      'Image Actions': 'images',
      'Load Balancers': 'load-balancers',
      'Load Balancer Actions': 'load-balancers',
      // No `load-balancer-types` family exists, and inventing one would put two
      // catalogue-lookup operations in a family of their own. They belong with
      // the resource they describe.
      'Load Balancer Types': 'load-balancers',
      Locations: 'locations',
      Networks: 'networks',
      'Network Actions': 'networks',
      'Placement Groups': 'placement-groups',
      Pricing: 'pricing',
      'Primary IPs': 'primary-ips',
      'Primary IP Actions': 'primary-ips',
      'SSH Keys': 'ssh-keys',
      Servers: 'servers',
      'Server Actions': 'servers',
      // Server types are their own family: "which server type should I pick"
      // is a question asked before any server exists, and burying the answer
      // inside `servers` puts it behind 33 operations about a specific machine.
      'Server Types': 'server-types',
      Volumes: 'volumes',
      'Volume Actions': 'volumes',
      Zones: 'zones',
      'Zone Actions': 'zones',
      // RRSets are the records inside a zone. Nobody looks for DNS records in a
      // family other than the one holding the zone they live in.
      'Zone RRSets': 'zones',
      'Zone RRSet Actions': 'zones',
    },
    hetzner: {
      'Storage Boxes': 'storage-boxes',
      'Storage Box Actions': 'storage-boxes',
      'Storage Box Types': 'storage-boxes',
      'Storage Box Snapshots': 'storage-boxes',
      'Storage Box Subaccounts': 'storage-boxes',
      'Storage Box Subaccount Actions': 'storage-boxes',
    },
    // `robot` is deferred. Its families (robot-servers, robot-ips, robot-boot,
    // robot-storage-boxes, robot-ordering) already exist in types.ts and are
    // intentionally distinct from the cloud ones.
  };

// ---------------------------------------------------------------------------
// Pagination and Action detection
// ---------------------------------------------------------------------------

/** Presence of either marks the operation as paginated. */
const PAGINATION_PARAMS: ReadonlySet<string> = new Set(['page', 'per_page']);

/**
 * A success response carrying one of these at the top level is returning an
 * Action rather than the finished resource. Detected from the spec rather than
 * listed, because 144 of 221 operations do this and a hand-list would be stale
 * within one upstream release.
 */
const ACTION_RESPONSE_PROPERTIES: ReadonlySet<string> = new Set(['action', 'actions']);

/**
 * How far into `allOf`/`oneOf`/`anyOf` the Action probe descends. Bounded on
 * purpose: the probe looks at the SHAPE OF THE ENVELOPE, and an `action` key
 * found six levels inside a nested resource is not the envelope — it would flag
 * every operation that merely mentions an Action somewhere in its payload.
 */
const ACTION_PROBE_DEPTH = 4;

// ---------------------------------------------------------------------------
// Schema pruning
// ---------------------------------------------------------------------------

/** Descriptions longer than this are dropped whole. Context budget beats prose. */
const MAX_DESCRIPTION_CHARS = 200;

/** Summaries are search text and are shown per result row; keep them one line. */
const MAX_SUMMARY_CHARS = 160;

/**
 * Keys copied verbatim. An allowlist, not a denylist: a denylist silently leaks
 * whatever OpenAPI adds next, and the whole point of this pass is a bounded
 * payload. Includes vocabulary the current specs do not use yet, so a future
 * upstream constraint is preserved rather than dropped.
 */
const SCALAR_SCHEMA_KEYS: ReadonlySet<string> = new Set([
  'type',
  'format',
  'title',
  'description',
  'required',
  'nullable',
  'deprecated',
  'readOnly',
  'writeOnly',
  'minimum',
  'maximum',
  'exclusiveMinimum',
  'exclusiveMaximum',
  'multipleOf',
  'minLength',
  'maxLength',
  'pattern',
  'minItems',
  'maxItems',
  'uniqueItems',
  'minProperties',
  'maxProperties',
]);

/** Keys whose value is itself a schema (or an array of schemas). */
const NESTED_SCHEMA_KEYS: ReadonlySet<string> = new Set([
  'items',
  'additionalProperties',
  'not',
  'oneOf',
  'anyOf',
  'allOf',
]);

/** Keys whose value is a map of property name -> schema. */
const SCHEMA_MAP_KEYS: ReadonlySet<string> = new Set(['properties', 'patternProperties']);

/**
 * Keys holding instance data rather than schemas. Copied untouched — running the
 * key allowlist over a `default: { ... }` value would mangle real data.
 */
const OPAQUE_SCHEMA_KEYS: ReadonlySet<string> = new Set(['default', 'const', 'enum']);

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const SCRIPT_DIR = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..');
const OUT_DIR = join(REPO_ROOT, 'src', 'generated');

const BANNER = [
  '// GENERATED FILE — DO NOT EDIT, run npm run codegen',
  `// Sources: ${SPEC_SOURCES.map((s) => `scripts/${s.file} (${s.surface})`).join(', ')}`,
  '',
].join('\n');

const METHOD_ORDER: readonly HttpMethod[] = ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'];

const SURFACE_ORDER: ReadonlyMap<Surface, number> = new Map(SURFACES.map((s, i) => [s, i]));

// ---------------------------------------------------------------------------
// Minimal spec shape — only the parts this generator reads
// ---------------------------------------------------------------------------

interface OpenApiParameter {
  name?: string;
  in?: string;
  required?: boolean;
  description?: string;
  schema?: unknown;
}

interface OpenApiOperation {
  operationId?: string;
  summary?: string;
  description?: string;
  tags?: string[];
  parameters?: OpenApiParameter[];
  requestBody?: { content?: Record<string, { schema?: unknown } | undefined> };
  responses?: Record<string, unknown>;
}

interface OpenApiSpec {
  info?: { version?: string };
  paths?: Record<string, Record<string, OpenApiOperation> | undefined>;
  components?: Record<string, unknown>;
}

interface LoadedSpec {
  surface: Surface;
  file: string;
  spec: OpenApiSpec;
  version: string;
  sha256: string;
}

interface RawOperation {
  id: string;
  surface: Surface;
  method: HttpMethod;
  path: string;
  /** `surface METHOD /path` — the key the override lists are written against. */
  route: string;
  op: OpenApiOperation;
  spec: OpenApiSpec;
}

/** Emitted per operation for `describe_operation` to render. */
interface ParamSchema {
  name: string;
  in: 'path' | 'query';
  required?: boolean;
  description?: string;
  schema?: unknown;
}

interface OperationSchema {
  params?: ParamSchema[];
  body?: unknown;
}

function fail(message: string): never {
  process.stderr.write(`\ncodegen FAILED: ${message}\n\n`);
  process.exit(1);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/**
 * Line endings are normalised before hashing. `.gitattributes` is supposed to
 * keep the vendored specs byte-identical across platforms, but the hash is the
 * thing CI compares — it should not be able to disagree between a Windows and a
 * Linux checkout because of a checkout rule that lives in a different file.
 */
function sha256Of(source: string): string {
  return createHash('sha256').update(source.replace(/\r\n/g, '\n')).digest('hex');
}

function loadSpec(source: SpecSource): LoadedSpec {
  const path = join(SCRIPT_DIR, source.file);
  if (!existsSync(path)) fail(`vendored spec is missing: scripts/${source.file}`);
  const text = readFileSync(path, 'utf8');
  const spec = JSON.parse(text) as OpenApiSpec;
  const version = spec.info?.version?.trim();
  if (!version) fail(`scripts/${source.file} has no info.version`);
  return { surface: source.surface, file: source.file, spec, version, sha256: sha256Of(text) };
}

function collectRawOperations(loaded: LoadedSpec): RawOperation[] {
  const collected: RawOperation[] = [];
  for (const [path, item] of Object.entries(loaded.spec.paths ?? {})) {
    for (const [verb, op] of Object.entries(item ?? {})) {
      const method = METHOD_ORDER.find((m) => m === verb.toUpperCase());
      if (method === undefined) continue;
      const id = op.operationId?.trim();
      if (!id) {
        fail(
          `${loaded.surface} ${verb.toUpperCase()} ${path} has no operationId — it cannot be addressed.`,
        );
      }
      collected.push({
        id,
        surface: loaded.surface,
        method,
        path,
        route: `${loaded.surface} ${method} ${path}`,
        op,
        spec: loaded.spec,
      });
    }
  }
  return collected;
}

// ---------------------------------------------------------------------------
// Text
// ---------------------------------------------------------------------------

/**
 * Hetzner writes its prose as Markdown: `[Zone](#tag/zones)`. The link target is
 * an anchor inside Hetzner's own docs site and means nothing here, but the label
 * is the noun a user would type, so the label survives and the syntax does not.
 */
function stripMarkdown(text: string): string {
  return text
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/[`*_]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function firstSentence(text: string): string {
  const match = /^[\s\S]*?[.!?](?=\s|$)/.exec(text.trim());
  return (match?.[0] ?? text).trim();
}

function truncate(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}…`;
}

/**
 * Unlike Coolify's spec, Hetzner's `summary` is a written sentence — "Create a
 * Server", "Change reverse DNS entry for this Server" — and is the better search
 * text. `description` is a page of Markdown including error tables, so it is
 * only the fallback and only its first sentence.
 */
function summaryFor(raw: RawOperation): string {
  const summary = stripMarkdown(raw.op.summary ?? '');
  const description = firstSentence(stripMarkdown(raw.op.description ?? ''));
  return truncate(summary || description || raw.id, MAX_SUMMARY_CHARS);
}

// ---------------------------------------------------------------------------
// $ref resolution
// ---------------------------------------------------------------------------

function resolveRef(spec: OpenApiSpec, ref: string): unknown {
  if (!ref.startsWith('#/')) fail(`external $ref is not supported: ${ref}`);
  let node: unknown = spec;
  for (const segment of ref.slice(2).split('/')) {
    if (!isRecord(node)) fail(`unresolvable $ref: ${ref}`);
    node = node[segment.replace(/~1/g, '/').replace(/~0/g, '~')];
  }
  if (node === undefined) fail(`unresolvable $ref: ${ref}`);
  return node;
}

function dereference(node: unknown, spec: OpenApiSpec, seen: ReadonlySet<string>): unknown {
  if (Array.isArray(node)) return node.map((child) => dereference(child, spec, seen));
  if (!isRecord(node)) return node;

  const ref = node['$ref'];
  if (typeof ref === 'string') {
    // A self-referential schema cannot be inlined. `type: object` is a truthful
    // stand-in: the generic execute path passes bodies through without
    // validating them, so the model loses detail here, never correctness.
    if (seen.has(ref)) return { type: 'object' };
    return dereference(resolveRef(spec, ref), spec, new Set([...seen, ref]));
  }

  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) out[key] = dereference(value, spec, seen);
  return out;
}

/** One level of `$ref`, for probes that must not inline a whole subtree. */
function shallowResolve(node: unknown, spec: OpenApiSpec, seen: ReadonlySet<string>): unknown {
  if (!isRecord(node)) return node;
  const ref = node['$ref'];
  if (typeof ref !== 'string' || seen.has(ref)) return node;
  return shallowResolve(resolveRef(spec, ref), spec, new Set([...seen, ref]));
}

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

function classifyDanger(raw: RawOperation, overrides: ReadonlySet<string>): DangerClass {
  if (raw.method === 'DELETE' || overrides.has(raw.route)) return 'destructive';
  if (raw.method === 'GET') return 'safe';
  return 'write';
}

function familyFor(raw: RawOperation): OperationFamily {
  const tags = raw.op.tags ?? [];
  const tag = tags[0];
  if (tag === undefined) {
    fail(`${raw.route} carries no OpenAPI tag, so it cannot be filed into a family.`);
  }
  const byTag = FAMILY_BY_TAG[raw.surface];
  if (byTag === undefined) {
    fail(
      `no FAMILY_BY_TAG entry for surface '${raw.surface}' — add one before vendoring its spec.`,
    );
  }
  const family = byTag[tag];
  if (family === undefined) {
    fail(
      `unmapped ${raw.surface} tag '${tag}' (${raw.route}).\n` +
        'Add it to FAMILY_BY_TAG. Do not fall back to `other` — `other` is for operations that ' +
        'genuinely have no home, not for a tag nobody has looked at yet.',
    );
  }
  return family;
}

function pathParamsOf(path: string): string[] {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1] ?? '');
}

function parametersOf(raw: RawOperation, where: 'path' | 'query'): OpenApiParameter[] {
  return (raw.op.parameters ?? []).filter(
    (p) => p.in === where && typeof p.name === 'string' && p.name.length > 0,
  );
}

function queryParamsOf(raw: RawOperation): string[] {
  return parametersOf(raw, 'query').map((p) => p.name ?? '');
}

function isPaginated(raw: RawOperation): boolean {
  return queryParamsOf(raw).some((name) => PAGINATION_PARAMS.has(name));
}

function bodySchemaOf(raw: RawOperation): unknown {
  return raw.op.requestBody?.content?.['application/json']?.schema;
}

/**
 * Top-level property names of a schema, following composition keywords only.
 * Deliberately not a deep walk — see ACTION_PROBE_DEPTH.
 */
function envelopeProperties(
  schema: unknown,
  spec: OpenApiSpec,
  depth: number,
  out: Set<string>,
): void {
  if (depth > ACTION_PROBE_DEPTH) return;
  const node = shallowResolve(schema, spec, new Set());
  if (!isRecord(node)) return;

  const properties = node['properties'];
  if (isRecord(properties)) for (const name of Object.keys(properties)) out.add(name);

  for (const key of ['allOf', 'oneOf', 'anyOf']) {
    const branches = node[key];
    if (!Array.isArray(branches)) continue;
    for (const branch of branches) envelopeProperties(branch, spec, depth + 1, out);
  }
}

/**
 * Hetzner mutations are asynchronous: the call returns `{ action: { status:
 * 'running' } }` and the work finishes later. A tool that returns that and stops
 * has told the model nothing about whether anything happened, so the tool layer
 * needs to know which operations behave this way — from the spec, because 144 of
 * 221 do and a hand-list would rot.
 */
function returnsAction(raw: RawOperation): boolean {
  const responses = raw.op.responses ?? {};
  for (const [code, response] of Object.entries(responses)) {
    if (!/^2\d\d$/.test(code)) continue;
    const resolved = shallowResolve(response, raw.spec, new Set());
    if (!isRecord(resolved)) continue;
    const content = resolved['content'];
    if (!isRecord(content)) continue;
    const json = content['application/json'];
    if (!isRecord(json)) continue;

    const properties = new Set<string>();
    envelopeProperties(json['schema'], raw.spec, 0, properties);
    for (const name of properties) if (ACTION_RESPONSE_PROPERTIES.has(name)) return true;
  }
  return false;
}

function toCatalogOperation(
  raw: RawOperation,
  overrides: ReadonlySet<string>,
  costly: ReadonlySet<string>,
): CatalogOperation {
  const row: CatalogOperation = {
    id: raw.id,
    surface: raw.surface,
    method: raw.method,
    path: raw.path,
    family: familyFor(raw),
    summary: summaryFor(raw),
    // Taken from the URL template, not from `parameters`: the template is what
    // the HTTP client must actually substitute, and specs under-declare.
    pathParams: pathParamsOf(raw.path),
    queryParams: queryParamsOf(raw),
    // Derived from the same lookup that emits the schema, so `hasBody === true`
    // and "getSchema(id).body exists" can never disagree.
    hasBody: bodySchemaOf(raw) !== undefined,
    danger: classifyDanger(raw, overrides),
  };
  if (costly.has(raw.route)) row.costly = true;
  if (returnsAction(raw)) row.returnsAction = true;
  if (isPaginated(raw)) row.paginated = true;
  return row;
}

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

function pruneSchema(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(pruneSchema);
  if (!isRecord(node)) return node;

  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    if (SCHEMA_MAP_KEYS.has(key)) {
      out[key] = pruneSchemaMap(value);
    } else if (NESTED_SCHEMA_KEYS.has(key)) {
      out[key] = pruneSchema(value);
    } else if (OPAQUE_SCHEMA_KEYS.has(key)) {
      out[key] = value;
    } else if (key === 'description') {
      if (typeof value === 'string') {
        const text = stripMarkdown(value);
        if (text.length > 0 && text.length <= MAX_DESCRIPTION_CHARS) out[key] = text;
      }
    } else if (SCALAR_SCHEMA_KEYS.has(key)) {
      out[key] = value;
    }
    // Everything else — `example`, `examples`, vendor extensions — is dropped.
  }
  return out;
}

/** Property names are data, so only the values run through the key allowlist. */
function pruneSchemaMap(node: unknown): unknown {
  if (!isRecord(node)) return pruneSchema(node);
  const out: Record<string, unknown> = {};
  for (const [name, schema] of Object.entries(node)) out[name] = pruneSchema(schema);
  return out;
}

function paramSchemasOf(raw: RawOperation): ParamSchema[] {
  const params: ParamSchema[] = [];
  for (const where of ['path', 'query'] as const) {
    for (const parameter of parametersOf(raw, where)) {
      const row: ParamSchema = { name: parameter.name ?? '', in: where };
      if (parameter.required === true) row.required = true;
      const description = stripMarkdown(parameter.description ?? '');
      if (description.length > 0) row.description = truncate(description, MAX_DESCRIPTION_CHARS);
      if (parameter.schema !== undefined) {
        row.schema = pruneSchema(dereference(parameter.schema, raw.spec, new Set()));
      }
      params.push(row);
    }
  }
  return params;
}

/**
 * What `describe_operation` renders. Parameters and body live here rather than
 * on `CatalogOperation` because inlining them into every search result would
 * blow the context budget the catalog exists to protect: search shows the row,
 * describe shows the shape.
 */
function buildSchemas(kept: readonly RawOperation[]): Record<string, OperationSchema> {
  const schemas: Record<string, OperationSchema> = {};
  for (const raw of kept) {
    const entry: OperationSchema = {};
    const params = paramSchemasOf(raw);
    if (params.length > 0) entry.params = params;
    const body = bodySchemaOf(raw);
    if (body !== undefined) entry.body = pruneSchema(dereference(body, raw.spec, new Set()));
    if (entry.params !== undefined || entry.body !== undefined) schemas[raw.id] = entry;
  }
  return schemas;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Column budget for keeping an array on one line. Matches prettier's default. */
const INLINE_WIDTH = 72;

function renderString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
  return `'${escaped}'`;
}

/**
 * Objects always expand and arrays collapse when they fit. That is prettier's
 * own shape, and it happens to be the readable choice: one field per line diffs
 * cleanly, while `pathParams: ['id']` on its own three lines would not.
 */
function renderValue(value: unknown, indent: string): string {
  if (typeof value === 'string') return renderString(value);
  if (typeof value === 'number' || typeof value === 'boolean' || value === null) {
    return String(value);
  }

  const inner = `${indent}  `;
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const parts = value.map((item) => renderValue(item, inner));
    const inline = `[${parts.join(', ')}]`;
    if (!inline.includes('\n') && indent.length + inline.length <= INLINE_WIDTH) return inline;
    return `[\n${parts.map((part) => `${inner}${part},`).join('\n')}\n${indent}]`;
  }

  if (isRecord(value)) {
    const entries = Object.entries(value).filter(([, v]) => v !== undefined);
    if (entries.length === 0) return '{}';
    const lines = entries.map(([key, v]) => {
      const renderedKey = IDENTIFIER.test(key) ? key : renderString(key);
      return `${inner}${renderedKey}: ${renderValue(v, inner)},`;
    });
    return `{\n${lines.join('\n')}\n${indent}}`;
  }

  return 'null';
}

function renderCatalog(rows: readonly CatalogOperation[]): string {
  return [
    BANNER,
    "import type { CatalogOperation } from '../types.js';",
    '',
    `export const CATALOG: CatalogOperation[] = ${renderValue(rows, '')};`,
    '',
  ].join('\n');
}

function renderSchemas(schemas: Record<string, OperationSchema>): string {
  return [
    BANNER,
    '/** A path or query parameter, as `describe_operation` renders it. */',
    'export interface ParamSchema {',
    '  name: string;',
    "  in: 'path' | 'query';",
    '  required?: boolean;',
    '  description?: string;',
    '  schema?: unknown;',
    '}',
    '',
    '/**',
    ' * Dereferenced, pruned parameter and request-body schemas for one operation.',
    ' * `body` is absent exactly when the operation takes no JSON body.',
    ' */',
    'export interface OperationSchema {',
    '  params?: ParamSchema[];',
    '  body?: unknown;',
    '}',
    '',
    '/** Keyed by operation id. An absent id takes neither parameters nor a body. */',
    `export const SCHEMAS: Record<string, OperationSchema> = ${renderValue(schemas, '')};`,
    '',
  ].join('\n');
}

function renderMeta(meta: CatalogMeta): string {
  return [
    BANNER,
    "import type { CatalogMeta } from '../types.js';",
    '',
    `export const METADATA: CatalogMeta = ${renderValue(meta, '')};`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Deterministic timestamp
// ---------------------------------------------------------------------------

const GENERATED_AT_PLACEHOLDER = '__GENERATED_AT__';

function readIfExists(path: string): string | undefined {
  return existsSync(path) ? readFileSync(path, 'utf8') : undefined;
}

/** Git may have handed us CRLF on checkout; that is not a content change. */
function sameContent(a: string | undefined, b: string): boolean {
  return a !== undefined && a.replace(/\r\n/g, '\n') === b.replace(/\r\n/g, '\n');
}

/**
 * `generatedAt` would otherwise dirty the tree on every run, and CI runs
 * `npm run codegen && git diff --exit-code src/generated`. So the stamp only
 * moves when the emitted content moves: re-running against unchanged specs is a
 * no-op.
 */
function resolveGeneratedAt(previousMeta: string | undefined, template: string): string {
  const now = new Date().toISOString();
  if (previousMeta === undefined) return now;
  const previousStamp = /generatedAt: '([^']*)'/.exec(previousMeta)?.[1];
  if (previousStamp === undefined) return now;
  const replayed = template.replace(
    renderString(GENERATED_AT_PLACEHOLDER),
    renderString(previousStamp),
  );
  return sameContent(previousMeta, replayed) ? previousStamp : now;
}

// ---------------------------------------------------------------------------
// Assertions
// ---------------------------------------------------------------------------

function assertRoutesMatched(
  label: string,
  declared: readonly string[],
  routes: ReadonlyMap<string, number>,
): void {
  const missing = declared.filter((route) => (routes.get(route) ?? 0) !== 1);
  if (missing.length > 0) {
    fail(
      `${label} lists ${missing.length} route(s) that do not match exactly one operation:\n` +
        missing.map((route) => `  ${route} (matched ${routes.get(route) ?? 0})`).join('\n') +
        '\nEither upstream moved them or a spec is wrong. Do not delete the entry to make this ' +
        'pass — find where the operation went first.',
    );
  }
  const duplicated = declared.filter((route, index) => declared.indexOf(route) !== index);
  if (duplicated.length > 0) fail(`${label} lists duplicate routes: ${duplicated.join(', ')}`);
}

/**
 * Ids address operations across every surface at once — the tool layer takes an
 * id, not an (id, surface) pair — so a collision between two specs would make
 * one of the two unreachable, silently and non-deterministically.
 */
function assertIdsUniqueAcrossSurfaces(rows: readonly CatalogOperation[]): void {
  const seen = new Map<string, CatalogOperation>();
  for (const row of rows) {
    const previous = seen.get(row.id);
    if (previous !== undefined) {
      fail(
        `operation id '${row.id}' is used by two surfaces:\n` +
          `  ${previous.surface} ${previous.method} ${previous.path}\n` +
          `  ${row.surface} ${row.method} ${row.path}\n` +
          'Ids must be unique across surfaces because the tool layer addresses operations by id ' +
          'alone. Qualify one of them before regenerating.',
      );
    }
    seen.set(row.id, row);
  }
}

function assertCatalogInvariants(rows: readonly CatalogOperation[]): void {
  if (rows.length === 0) fail('catalog is empty');
  assertIdsUniqueAcrossSurfaces(rows);

  for (const row of rows) {
    if (row.danger === 'safe' && row.method !== 'GET') {
      fail(`${row.id} is classified safe but is a ${row.method}`);
    }
    if (row.danger !== 'safe' && row.method === 'GET') {
      fail(`${row.id} is a GET but is classified ${row.danger}`);
    }
    if (row.method === 'DELETE' && row.danger !== 'destructive') {
      fail(`${row.id} is a DELETE but is classified ${row.danger}`);
    }
    if (row.hasBody && row.method === 'GET') fail(`${row.id} is a GET that declares a body`);
    if (row.costly === true && row.method === 'GET') {
      fail(`${row.id} is a GET flagged costly — reading something cannot open a bill`);
    }
    if (row.summary.trim().length === 0) fail(`${row.id} has no summary`);
    const declared = [...row.pathParams].sort().join(',');
    const actual = pathParamsOf(row.path).sort().join(',');
    if (declared !== actual) fail(`${row.id} pathParams (${declared}) do not match its template`);
  }
}

function assertSchemaCoverage(
  rows: readonly CatalogOperation[],
  schemas: Record<string, OperationSchema>,
): void {
  const withBody = new Set(rows.filter((r) => r.hasBody).map((r) => r.id));
  const withBodySchema = new Set(
    Object.entries(schemas)
      .filter(([, entry]) => entry.body !== undefined)
      .map(([id]) => id),
  );
  const missing = [...withBody].filter((id) => !withBodySchema.has(id));
  const extra = [...withBodySchema].filter((id) => !withBody.has(id));
  if (missing.length > 0) fail(`hasBody without a body schema: ${missing.join(', ')}`);
  if (extra.length > 0) fail(`body schema without hasBody: ${extra.join(', ')}`);

  const ids = new Set(rows.map((r) => r.id));
  const orphans = Object.keys(schemas).filter((id) => !ids.has(id));
  if (orphans.length > 0) fail(`schema without a catalog row: ${orphans.join(', ')}`);
}

/**
 * The pagination and Action probes are the two derivations with no independent
 * witness — nothing downstream would fail loudly if they started returning
 * `false` for everything. So they are pinned to a count and to a known-true
 * example rather than trusted.
 */
function assertProbesStillWork(rows: readonly CatalogOperation[]): void {
  const paginatedCloudGets = rows.filter(
    (r) => r.surface === 'cloud' && r.method === 'GET' && r.paginated === true,
  ).length;
  if (paginatedCloudGets !== EXPECTED_PAGINATED_CLOUD_GETS) {
    fail(
      `expected ${EXPECTED_PAGINATED_CLOUD_GETS} paginated cloud GETs, found ${paginatedCloudGets}.\n` +
        'Either upstream changed its pagination parameters or the detector broke. Check which ' +
        'before touching EXPECTED_PAGINATED_CLOUD_GETS.',
    );
  }

  // `create_server` is the canonical asynchronous mutation: it returns
  // `{ server, action, next_actions }` and the server is not usable until the
  // action finishes. If this stops being detected, the probe is broken.
  const createServer = rows.find((r) => r.id === 'create_server');
  if (createServer?.returnsAction !== true) {
    fail('the returnsAction probe no longer detects create_server, which returns an Action.');
  }

  // A pure catalogue read returns no Action. If this starts being detected, the
  // probe has widened into "mentions an action anywhere" and is worthless.
  const listServerTypes = rows.find((r) => r.id === 'list_server_types');
  if (listServerTypes !== undefined && listServerTypes.returnsAction === true) {
    fail('the returnsAction probe now flags list_server_types, which returns no Action.');
  }
}

// ---------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------

function printTable(title: string, rows: ReadonlyArray<readonly [string, string]>): void {
  if (rows.length === 0) return;
  const width = Math.max(...rows.map(([label]) => label.length));
  const lines = rows.map(([label, value]) => `  ${label.padEnd(width)}  ${value}`);
  process.stdout.write(`\n${title}\n${lines.join('\n')}\n`);
}

function countBy<T extends string>(values: readonly T[]): Array<readonly [string, string]> {
  const counts = new Map<string, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([key, count]) => [key, String(count)] as const);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const loaded = SPEC_SOURCES.map(loadSpec);

  const rawOperations: RawOperation[] = [];
  for (const [index, spec] of loaded.entries()) {
    const source = SPEC_SOURCES[index];
    if (source === undefined) fail('spec source table went out of sync with the loaded specs');
    const operations = collectRawOperations(spec);
    if (operations.length !== source.expectedOperations) {
      fail(
        `expected ${source.expectedOperations} operations in scripts/${source.file}, found ` +
          `${operations.length}.\nThe vendored spec changed. Review the diff, then update the ` +
          'pinned count in the same commit — never adjust it to silence this.',
      );
    }
    rawOperations.push(...operations);
  }

  const routeCounts = new Map<string, number>();
  for (const raw of rawOperations)
    routeCounts.set(raw.route, (routeCounts.get(raw.route) ?? 0) + 1);
  assertRoutesMatched('DESTRUCTIVE_OVERRIDE_ROUTES', DESTRUCTIVE_OVERRIDE_ROUTES, routeCounts);
  assertRoutesMatched('COSTLY_ROUTES', COSTLY_ROUTES, routeCounts);

  const overrides = new Set(DESTRUCTIVE_OVERRIDE_ROUTES);
  const costly = new Set(COSTLY_ROUTES);

  // Sorted so the emitted file is a function of the specs alone: `git diff
  // --exit-code src/generated` is only meaningful if key order is stable.
  const ordered = [...rawOperations].sort(
    (a, b) =>
      (SURFACE_ORDER.get(a.surface) ?? 0) - (SURFACE_ORDER.get(b.surface) ?? 0) ||
      a.path.localeCompare(b.path) ||
      METHOD_ORDER.indexOf(a.method) - METHOD_ORDER.indexOf(b.method) ||
      a.id.localeCompare(b.id),
  );

  const rows = ordered
    .map((raw) => toCatalogOperation(raw, overrides, costly))
    .sort(
      (a, b) =>
        (SURFACE_ORDER.get(a.surface) ?? 0) - (SURFACE_ORDER.get(b.surface) ?? 0) ||
        a.family.localeCompare(b.family) ||
        a.path.localeCompare(b.path) ||
        METHOD_ORDER.indexOf(a.method) - METHOD_ORDER.indexOf(b.method) ||
        a.id.localeCompare(b.id),
    );

  assertCatalogInvariants(rows);
  assertProbesStillWork(rows);

  const schemas = buildSchemas(ordered);
  assertSchemaCoverage(rows, schemas);

  const catalogSource = renderCatalog(rows);
  const schemasSource = renderSchemas(schemas);
  const metaTemplate = renderMeta({
    specs: loaded.map((spec) => ({
      surface: spec.surface,
      version: spec.version,
      sha256: spec.sha256,
      operationCount: rows.filter((row) => row.surface === spec.surface).length,
    })),
    operationCount: rows.length,
    generatedAt: GENERATED_AT_PLACEHOLDER,
  });

  const catalogPath = join(OUT_DIR, 'catalog.ts');
  const schemasPath = join(OUT_DIR, 'schemas.ts');
  const metaPath = join(OUT_DIR, 'meta.ts');

  const unchangedElsewhere =
    sameContent(readIfExists(catalogPath), catalogSource) &&
    sameContent(readIfExists(schemasPath), schemasSource);
  const generatedAt = unchangedElsewhere
    ? resolveGeneratedAt(readIfExists(metaPath), metaTemplate)
    : new Date().toISOString();
  const metaSource = metaTemplate.replace(
    renderString(GENERATED_AT_PLACEHOLDER),
    renderString(generatedAt),
  );

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(catalogPath, catalogSource, 'utf8');
  writeFileSync(schemasPath, schemasSource, 'utf8');
  writeFileSync(metaPath, metaSource, 'utf8');

  printTable(
    'hetzner-mcp catalog',
    loaded.map(
      (spec) =>
        [
          `${spec.surface} spec`,
          `v${spec.version}  ${spec.sha256.slice(0, 16)}…  ${rows.filter((r) => r.surface === spec.surface).length} ops`,
        ] as const,
    ),
  );
  printTable('totals', [
    ['operations', String(rows.length)],
    ['body schemas', String(rows.filter((r) => r.hasBody).length)],
    ['paginated', String(rows.filter((r) => r.paginated === true).length)],
    ['returns action', String(rows.filter((r) => r.returnsAction === true).length)],
    ['costly', String(rows.filter((r) => r.costly === true).length)],
    ['generated at', generatedAt],
  ]);
  printTable('by danger', countBy(rows.map((r) => r.danger)));
  printTable('by method', countBy(rows.map((r) => r.method)));
  printTable('by family', countBy(rows.map((r) => r.family)));
  printTable(
    'destructive but not DELETE',
    rows
      .filter((r) => r.danger === 'destructive' && r.method !== 'DELETE')
      .map((r) => [r.id, `${r.surface} ${r.method} ${r.path}`] as const),
  );
  process.stdout.write(`\nwrote ${catalogPath}\n      ${schemasPath}\n      ${metaPath}\n\n`);
}

main();
